### ISSUE TITLE
GZ-DECaLS-dataset.ipynb Missing CSV datasets

### ISSUE THREAD

**Issue by JosephKarpinski** [henrysky/Galaxy10#1]
Haven't been able to locate:

FileNotFoundError: result_ab.csv not found.

FileNotFoundError: result_c.csv not found.

In GZ2-SDSS-dataset.ipynb:
FileNotFoundError: [Errno 2] No such file or directory: 'gz2_hart16_modded.csv'

**Comment by henrysky** [comment]
I think `result_ab.csv` and `result_c.csv` were renamed to `edges_result_ab.csv` and `edges_result_c.csv` which are generated in `CCD-Artifacts.ipynb`. Sorry about that.

`gz2_hart16_modded.csv` was generated in `GZ2-SDSS-dataset.ipynb`
