### ISSUE TITLE
Simple question about Galaxy10 datasets

### ISSUE THREAD

**Issue by lucienwi** [henrysky/Galaxy10#2]
Hello, I am currently writing a master thesis in statistics and I am using the Galaxy10 DECaLS dataset to test different state-of-the-art CNN architectures, a sort of a review of the field in galaxy morphology classification.

Your dataset has been great to play with, but I had a simple question. Did you "build" it to use for your more advanced astrophysical researchs or is it only usable for galaxy classification?

Thanks in advance for your answer.

**Comment by henrysky** [comment]
Glad to hear Galaxy10 is useful in your work.

I did not build it to be used in my own scientific research (most of my own research deal with 1D data). Just a little project to help others interested in deep learning application in astronomy to have a toy dataset for learning like MNIST or CIFAR10.

Galaxy classification probably is the only thing you can do for supervised learning with the information I have provided in this GitHub repository, or unsupervised learning where you only need the images. But cross-matching with external datasets/tables, I would assume you can also do other things like getting galaxy detailed morphorlogy/mass/z/star formation rate etc.
