### ISSUE TITLE
Downloading as a zip file?

### ISSUE THREAD

**Issue by rosa-martin** [henrysky/Galaxy10#3]
Is it possible to download Galaxy10 DECals Dataset as a zip file with the images? I don't have enough RAM on my PC to load all of these images from the .h5 file using h5py. I'd prefer to have these images on my hard disk and load them individually using something like opencv.

Thanks

**Comment by henrysky** [comment]
Here is a memory efficient code to save all images in the .h5 file to .png (be careful not to use .jpg as lossy compression will be applied). If your computer still have issue with the code, I am happy to do it and send all the images to you.

```python
import h5py
import tqdm
from PIL import Image

f = h5py.File("Galaxy10_DECals.h5", "r")

for idx in tqdm.tqdm(range(len(f["images"]))):
    im = Image.fromarray(f["images"][idx])
    im.save(f"{idx}.png")
```

**Comment by rosa-martin** [comment]
Thanks a lot. The code did exactly what I needed.

> Here is a memory efficient code to save all images in the .h5 file to .png (be careful not to use .jpg as lossy compression will be applied). If your computer still have issue with the code, I am happy to do it and send all the images to you.
> 
> ```python
> import h5py
> import tqdm
> from PIL import Image
> 
> f = h5py.File("Galaxy10_DECals.h5", "r")
> 
> for idx in tqdm.tqdm(range(len(f["images"]))):
>     im = Image.fromarray(f["images"][idx])
>     im.save(f"{idx}.png")
> ```
